# This file should be placed in your home directory

#autoloaders:
  # Namespace => path to your libs
#  ProjectEight: /Users/projecteight/PhpStormProjects/projecteight-magerun/src

commands:
  customCommands:
    - ProjectEight\Magento\Command\Developer\Environment\SetCommand

#
# Adapt the following example as necessary to fit your requirements
#

#  ProjectEight\Magento\Command\Developer\Environment\SetCommand:
#    environments:
#      localhost:
#        config:
#          default:
#            0:
#              general/country/default: GB
#              general/store_information/merchant_country: FR
#              design/head/demonotice: 1
#              trans_email/ident_general/email: projecteight@example.com
#              trans_email/ident_sales/email: projecteight@example.com
#              trans_email/ident_support/email: projecteight@example.com
#              trans_email/ident_custom1/email: projecteight@example.com
#              trans_email/ident_custom2/email: projecteight@example.com
#              contacts/email/recipient_email: projecteight@example.com
#              sitemap/generate/error_email: projecteight@example.com
#              customer/password/require_admin_user_to_change_user_password: 0
#              tax/defaults/country: GB
#              tax/defaults/postcode: "YO24 1BF"
#              shipping/origin/country_id: GB
#              shipping/origin/region_id: North Yorkshire
#              shipping/origin/postcode: "YO24 1BF"
##              Shipping methods:
#              carriers/dhlint/active: 0
#              carriers/dhl/active: 0
#              carriers/fedex/active: 0
#              carriers/usps/active: 0
#              carriers/ups/active: 0
#              google/analytics/account: UA-123456-AB
#              payment/account/merchant_country: GB
#              payment/settings_ec/payment_action: Sale
#              payment/settings_ec_advanced/debug: 1
##              Other payment methods:
#              payment/checkmo/active: 1
#              payment/checkmo/specificcountry: GB,DE
#              admin/security/extensions_compatibility_mode: Disabled
#              system/smtp/disable: 1
#              dev/log/active: 1
#              dev/restrict/allow_ips: 127.0.0.1
#      dev:
#        config:
#          websites: # Example of setting values in the websites scope
#            1:
#              general/country/default: FR
#          stores: # Example of setting values in the stores scope
#            3:
#              general/country/default: DE
